### ISSUE TITLE
Make a separate branch for rust stable!

### ISSUE THREAD

**Issue by shackra** [raymontag/rust-keepass#5]
Just that. If there is no technical limitation to do this, obviously.

**Comment by raymontag** [comment]
There is now a stable branch that I will maintain separate until nightly is not needed anymore. ATM volatile intrinsics are not supported by stable (see #4)

**Comment by mathstuf** [comment]
And it looks like they'll never be stable. Looks like the best way is to use FFI bindings to use C code to do the memset. See [this Reddit post](https://www.reddit.com/r/rust/comments/31f03s/questions_on_how_to_make_sodiumoxide_rustbeta/).

**Comment by raymontag** [comment]
Thank you. I already knew the thread on reddit and think that I could implement something like this in the future. However I should finish the core functionality of the crate first :)
